openapi: 3.0.3
info:
  title: Rescue S.M.S API
  description: |-
    API documentation for the School Management System tagged Project Rescue.

  contact:
    email: asongrandy9@gmail.com
  version: 1.0.0
servers:
  - url: https://rescue-backend.onrender.com
tags:
  - name: Profile
    description: Information about the User Profile
  - name: Student
    description: Operations related to handling Student info and data
  - name: Health
    description: Api health status
paths:
  /api/health:
    get:
      tags:
       - Health
      summary: Test Api Health/Active
      description: To Test Api health
      responses: 
        '200' :
          description: OK
        '405' :
          description: Down
  /profile/all:
    get:
      tags:
        - Profile
      summary: Get all User Profiles
      description: For administrator related activities to view all user profiles
      operationId: getAllProfiles
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
        '400': 
          description: Database validation error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /profile/new:
    post:
      tags:
        - Profile
      summary: Register a new User profile
      description: Add a new profile
      operationId: addProfile
      requestBody:
        description: Create a new profile
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'          
        '405':
          description: Invalid input
  /profile/login:
    post:
      tags:
        - Profile
      summary: Login to an existing User profile
      description: Basically getting user profile info
      operationId: loginProfile
      requestBody:
        description: Login to profile
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: User Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /profile/update:
    put:
      tags:
        - Profile
      summary: Update an existing User profile
      description: Update User Profile Info
      operationId: updateProfile
      requestBody:
        description: Update profile
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true
      responses:
        '200':
          description: Updated
        '400':
          description: User Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /profile/delete/{profile_id}:
    delete:
      tags:
        - Profile
      summary: Delete an existing User profile
      description: Delete User Profile Info
      operationId: deleteProfile
      parameters:
        - name: profile_id
          in: path
          description: The id for the profile to be deleted
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted
        '400':
          description: Database Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
components:
  schemas:
    Profile:
      required:
        - fname
        - lname
        - dob
        - phone
        - email
        - password
      type: object
      properties:
        profile_id:
          type: string
          example: 69a4c257-6e2b-4ec0-8ccd-049da7717a10
        fname:
          type: string
          example: Thaxter
        lname:
          type: string
          example: Zaczek
        dob:
          type: string
          example: 2021-08-08
        phone:
          type: number
          example: 673458932
        email: 
          type: string
          example: tzac0@hubpages.com
        password:
          type: string
          example: $2b$10$Ip04QRPSCqn6MdA5s29x7uIw2H9NDD0VKNEbZ3JQJt/R2/uWZzRl.
        avatar:
          type: string
          example: https://robohash.org/fugiatquinihil.png?size=50x50&set=set1
        address:
          type: string
          example: 0494 Nelson Plaza
    Error:
      type: object
      properties:
        error:
          type: string
          example: Validation Error
    Student:
      required:
        - student_id
        - profile_id
        - place_of_birth
        - matriculation_number
        - status
        - cycle_id
        - department_id
        - date_of_admission
        - program_id
        - mothers_name
        - sponsors_name
        - sponsors_tel
        - sponsors_email
        - emergency_name
        - emergency_tel
        - emergency_email
        
      type: object
      properties:
        student_id:
          type: string
          example: 69a4c257-6e2b-4ec0-8ccd-049da7717a10
        profile_id:
          type: string
          example: 69a4c257-6e2b-4ec0-8ccd-049da7717a10
        cycle_id:
          type: string
          example: 69a4c257-6e2b-4ec0-8ccd-049da7717a10
        department_id:
          type: string
          example: 69a4c257-6e2b-4ec0-8ccd-049da7717a10
        program_id:
          type: string
          example: 69a4c257-6e2b-4ec0-8ccd-049da7717a10
        place_of_birth:
          type: string
          example: Limbe
        matriculation_number:
          type: string
          example: HTC011
        date_of_admission:
          type: string
          example: 2021-08-08
        sponsors_tel:
          type: number
          example: 673458932
        sponsors_email: 
          type: string
          example: tzac0@hubpages.com
        sponsors_name: 
          type: string
          example: tzac
        emergency_tel:
          type: number
          example: 673458932
        emergency_email: 
          type: string
          example: tzac0@hubpages.com
        emergency_name: 
          type: string
          example: tzac
        mothers_name:
          type: string
          example: Tcaslt
        status:
          type: string
          example: PENDING
        institution_email: 
          type: string
          example: tzac0@hubpages.com
        fathers_name:
          type: string
          example: Tcaslt
        emergency_address: 
          type: string
          example: 0494 Nelson Plaza
        profile:
          type: object
          items:
            $ref: '#/components/schemas/Profile'
    LoginResponse:
      type: object
      properties:
        profile:
            $ref: '#/components/schemas/Profile'
        key:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlIjp7InByb2ZpbGVfaWQiOiI2OWE0YzI1Ny02ZTJiLTRlYzAtOGNjZC0wNDlkYTc3MTdhMTAiLCJmbmFtZSI6IlRoYXh0ZXIiLCJsbmFtZSI6IlphY3playIsImRvYiI6IjIwMjEtMDgtMDgiLCJwaG9uZSI6Njc1NzQwMjA2LCJlbWFpbCI6InR6YWMwQGh1YnBhZ2VzLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJElwMDRRUlBTQ3FuNk1kQTVzMjl4N3VJdzJIOU5ERDBWS05FYlozSlFKdC9SMi91V1p6UmwuIiwiYXZhdGFyIjoiaHR0cHM6Ly9yb2JvaGFzaC5vcmcvZnVnaWF0cXVpbmloaWwucG5nP3NpemU9NTB4NTAmc2V0PXNldDEiLCJhZGRyZXNzIjoiMDQ5NCBOZWxzb24gUGxhemEiLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTIwVDA3OjUzOjAxLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTIwVDA3OjUzOjAxLjAwMFoifSwiaWF0IjoxNjc5Mjk5MDI2fQ.K1eUkYIVHo6rhsFnM1HQLY3afk1WLNTZRAJ4DZTBZjI